# apiVersion: skaffold/v2alpha3
# kind: Config
# build:
#   local:
#     push: false
#   artifacts:
#     - image: bankole2000/cp-auth
#       context: packages/auth-service
#       sync: 
#         manual:
#           - dest: .
#             src: src/**/*.ts
#       docker: 
#         dockerfile: Dockerfile
# manifests: 
#   rawYaml: 
#   - ./infra/k8s/*
# deploy: 
#   kubectl:
#     {}

# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   local: 
#     push: false
#   artifacts:
#     - image: bankole2000/cp-auth
#       context: packages/auth-service
#       docker: 
#         dockerfile: Dockerfile
#       sync: 
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .

apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: bankole2000/cp-auth
      context: packages/auth-service
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .