export const socketEventTypes = {
  USER_CONNECTED: 'USER_CONNECTED',
  POST_CONNECTED: 'POST_CONNECTED',
  POST_PUBLISHED: 'POST_PUBLISHED',
  SEARCH_TAGS: 'SEARCH_TAGS',
  COMMENT_LIKED: 'COMMENT_LIKED',
  COMMENT_REPLY_LIKED: 'COMMENT_REPLY_LIKED',
  COMMENT_UNLIKED: 'COMMENT_UNLIKED',
  COMMENT_REPLY_UNLIKED: 'COMMENT_REPLY_UNLIKED',
  POST_LIKED: 'POST_LIKED',
  POST_UNLIKED: 'POST_UNLIKED',
  GET_REPOST_COUNT: 'GET_REPOST_COUNT',
  POST_REPOSTED: 'POST_REPOSTED',
  REPOST_UNDONE: 'REPOST_UNDONE',
  COMMENT_PUBLISHED: 'COMMENT_PUBLISHED',
  COMMENT_REPLY_PUBLISHED: 'COMMENT_REPLY_PUBLISHED',
  GET_NEW_COMMENT: 'GET_NEW_COMMENT'
};
