export const socketEventTypes = {
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  FOLLOWED_YOU: 'FOLLOWED_YOU',
  YOU_FOLLOWED: 'YOU_FOLLOWED',
  UNFOLLOWED_YOU: 'UNFOLLOWED_YOU',
  YOU_UNFOLLOWED: 'YOU_UNFOLLOWED',
  BLOCKED_YOU: 'BLOCKED_YOU',
  YOU_BLOCKED: 'YOU_BLOCKED',
  UNBLOCKED_YOU: 'UNBLOCKED_YOU',
  YOU_UNBLOCKED: 'YOU_UNBLOCKED',
  SENT_FOLLOW_REQUEST: 'SENT_FOLLOW_REQUEST',
  CANCELLED_FOLLOW_REQUEST: 'CANCELLED_FOLLOW_REQUEST',
  DECLINED_FOLLOW_REQUEST: 'DECLINED_FOLLOW_REQUEST',
  ACCEPTED_FOLLOW_REQUEST: 'ACCEPTED_FOLLOW_REQUEST',
  FOLLOW_REQUEST_DECLINED: 'FOLLOW_REQUEST_DECLINED',
  FOLLOW_REQUEST_ACCEPTED: 'FOLLOW_REQUEST_ACCEPTED',
  TAGGABLE_PROFILES: 'TAGGABLE_PROFILES'
};
